fix: make backlightctl dynamic based on brightness scale

diff --git a/bin/backlightctl b/bin/backlightctl
--- a/bin/backlightctl
+++ b/bin/backlightctl
@@ -1,17 +1,35 @@
 #!/bin/sh
+#
+# Change display device backlight via 'up', and 'down'
+#
+# A value can be provided as the second argument in order to control the
+# percent delta of the brightness modification
 
-BACKLIGHTDEVICE=$(ls /sys/class/backlight/)
+backlight_dev_dir=$(realpath /sys/class/backlight/*)
 
-BRIGHTNESS_INTERVAL=$2
+current_brightness=$(cat "${backlight_dev_dir}/brightness")
+max_brightness=$(cat "${backlight_dev_dir}/max_brightness")
 
-current_brightness=$(cat "/sys/class/backlight/$BACKLIGHTDEVICE/brightness")
+interval=$((max_brightness / 100))
+
+if [ "$2" ]; then
+    brightness_percent_delta=$2
+else
+    brightness_percent_delta=1
+fi
 
 up() {
-    sudo sh -c "echo $((current_brightness + BRIGHTNESS_INTERVAL)) > /sys/class/backlight/$BACKLIGHTDEVICE/brightness"
+    sudo sh -c "echo $((current_brightness + (interval * brightness_percent_delta))) > ${backlight_dev_dir}/brightness"
 }
 
 down() {
-    sudo sh -c "echo $((current_brightness - BRIGHTNESS_INTERVAL)) > /sys/class/backlight/$BACKLIGHTDEVICE/brightness"
+    sudo sh -c "echo $((current_brightness - (interval * brightness_percent_delta))) > ${backlight_dev_dir}/brightness"
 }
 
-$1
+case $1 in
+    up|down) $1 ;;
+    *)
+        echo >&2 "Error: Unsupoorted option $1. Valid options are: [up, down]"
+        exit 1
+        ;;
+esac
