fix: support brightness change on external monitors

diff --git a/bin/backlightctl b/bin/backlightctl
--- a/bin/backlightctl
+++ b/bin/backlightctl
@@ -1,9 +1,9 @@
-#!/bin/sh
+#!/bin/bash
 #
-# Change display device backlight via 'up', and 'down'
+# Change display device backlight via 'up', 'down', and 'change'
 #
-# A value can be provided as the second argument in order to control the
-# percent delta of the brightness modification
+# A value can be provided as the second argument to 'up' and 'down' in order to
+# control the percent delta of the brightness modification
 
 notify_echo() {
   echo "$1"
@@ -15,9 +15,20 @@ notify_echo() {
   exit 1
 }
 
-backlight_dev_dir=$(realpath /sys/class/backlight/*)
+hash ddcutil 2>/dev/null || {
+  notify_echo >&2 "Error: ddcutil must be installed for external monitor control."
+  exit 1
+}
 
-UID=$(id -u)
+backlight_dev_dir=/sys/class/backlight
+backlight_devs=$(ls /sys/class/backlight)
+
+ddc_displays=$(ddcutil detect | awk '/^Display/{print $2}')
+
+[ $backlight_devs ] || [ $ddc_displays ] || {
+  echo "Error: No configurable displays found! Sorry :("
+  exit 1
+}
 
 [ "$UID" -eq 0 ] || {
   user_in_video=false
@@ -29,44 +40,98 @@ UID=$(id -u)
   }
 }
 
-[ -f /etc/udev/rules.d/backlight.rules ] || {
+if [ $backlight_devs ] && [ ! -f /etc/udev/rules.d/backlight.rules ]; then
   [ "$UID" -eq 0 ] || {
     notify_echo >&2 "Error: This script must be run as root while setting up the udev rule"
     exit 1
   }
   mkdir -p /etc/udev/rules.d
 
-  cat <<EOF >/etc/udev/rules.d/backlight.rules
-ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video  ${backlight_dev_dir}/brightness", RUN+="/bin/chmod g+w ${backlight_dev_dir}/brightness"
+  for dev in $backlight_devs; do
+    cat <<EOF >/etc/udev/rules.d/backlight.rules
+ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video  ${backlight_dev_dir}/${dev}/brightness", RUN+="/bin/chmod g+w ${backlight_dev_dir}/${dev}/brightness"
 EOF
+  done
 
   notify_echo "You'll need to reboot before the udev rule takes effect"
   touch /tmp/new_backlightctl_udev_rule
   exit 0
-}
-
-current_brightness=$(cat "${backlight_dev_dir}/brightness")
-max_brightness=$(cat "${backlight_dev_dir}/max_brightness")
-
-interval=$((max_brightness / 100))
+fi
 
 brightness_percent_delta=1
 [ "$2" ] && brightness_percent_delta=$2
 
 get() {
-  echo $((current_brightness * 100 / max_brightness))
+  [ $backlight_devs ] && {
+    local current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
+    local max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
+    local interval=$((max_brightness / 100))
+
+    for dev in $backlight_devs; do
+      echo $((current_brightness * 100 / max_brightness))
+    done
+  }
+
+  for display in $ddc_displays; do
+    ddcutil get 10 --display $display
+  done
 }
 
 up() {
-  echo $((current_brightness + (interval * brightness_percent_delta))) >"${backlight_dev_dir}/brightness"
+  [ $backlight_devs ] && {
+    local current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
+    local max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
+    local interval=$((max_brightness / 100))
+
+    for dev in $backlight_devs; do
+      echo $((current_brightness + (interval * brightness_percent_delta))) >"${backlight_dev_dir}/${dev}/brightness"
+    done
+  }
+
+  for display in $ddc_displays; do
+    display_brightness=$(ddcutil get 10 --display $display)
+    ddcutil set 10 40 --display $display
+  done
 }
 
 down() {
-  echo $((current_brightness - (interval * brightness_percent_delta))) >"${backlight_dev_dir}/brightness"
+  [ $backlight_devs ] && {
+    local current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
+    local max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
+    local interval=$((max_brightness / 100))
+
+    for dev in $backlight_devs; do
+      echo $((current_brightness - (interval * brightness_percent_delta))) >"${backlight_dev_dir}/${backlight_devs}/brightness"
+    done
+  }
+
+  for display in $ddc_displays; do
+    display_brightness=$(ddcutil get 10 --display $display)
+    ddcutil set 10 40 --display $display
+  done
+}
+
+change() {
+  new_percent=$(seq 1 100 | fuzzel -d -p "new brightness >")
+
+  [ $backlight_devs ] && {
+    local current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
+    local max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
+    local interval=$((max_brightness / 100))
+
+    for dev in $backlight_devs; do
+      echo $((new_percent * interval)) >"${backlight_dev_dir}/${backlight_devs}/brightness"
+    done
+  }
+
+  for display in $ddc_displays; do
+    display_brightness=$(ddcutil get 10 --display $display)
+    ddcutil set 10 $new_percent --display $display
+  done
 }
 
 case $1 in
-up | down | get) $1 ;;
+up | down | change | get) $1 ;;
 *)
   echo >&2 "Error: Unsupported option $1. Valid options are: [up, down, get]"
   exit 1
diff --git a/bin/lockman b/bin/lockman
--- a/bin/lockman
+++ b/bin/lockman
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# TODO: Make a wallpaper tagger/finder (fzf that bitch?)
+# TODO: Make a wallpaper tagger/finder (fzf/telescope that bitch?)
 
 # shellcheck disable=1091
 [ "$XDG_CACHE_HOME" ] || XDG_CACHE_HOME=$HOME/.cache
@@ -12,38 +12,45 @@ wal_path=$(cat $XDG_CACHE_HOME/wal/wal)
 wal_name=$(echo $wal_path | awk -F/ '{print $NF}')
 
 make_blur_lock_screen() {
-  [ -f "/tmp/$wal_name" ] ||
-    convert -scale 10% -blur 0x2.5 -resize 1000% $wal_path /tmp/$wal_name
+    [ -f "/tmp/$wal_name" ] \
+        || convert -scale 10% -blur 0x2.5 -resize 1000% $wal_path /tmp/$wal_name
 }
 
 case $XDG_CURRENT_DESKTOP in
-sway | *yprland)
-  # resolution=$(swaymsg -t get_outputs |
-  #   jq '.[].current_mode | (.width|tostring) + "x" + (.height|tostring)' |
-  #   tr -d \")
+    *yprland)
+        hash hyprlock 2>/dev/null || {
+            echo "Error: hyprlock is not installed"
+            exit 1
+        }
+        hyprlock
+        ;;
+    sway)
+        # resolution=$(swaymsg -t get_outputs |
+        #   jq '.[].current_mode | (.width|tostring) + "x" + (.height|tostring)' |
+        #   tr -d \")
 
-  make_blur_lock_screen
+        make_blur_lock_screen
 
-  # S"AYSOCK=/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock swaymsg 'output * dpms off'
-  # shellcheck disable=2154
-  # swaylock-effects arch pkg
+        # S"AYSOCK=/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock swaymsg 'output * dpms off'
+        # shellcheck disable=2154
+        # swaylock-effects arch pkg
 
-  swaylock -f -K -i "/tmp/$wal_name" \
-    --font "mononoki Nerd Font" --font-size 30 \
-    --indicator-idle-visible --indicator-radius 100 --indicator-thickness 10 \
-    --ring-color "$color13" \
-    --text-color "$color15" \
-    --key-hl-color "$color12" \
-    --line-color "$color8" \
-    --inside-color "$color8" \
-    --separator-color "$color0" \
-    --inside-clear-color "$color11" --line-clear-color "$color12" --ring-clear-color "$color13"
-  # S"AYSOCK=/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock swaymsg 'output * dpms on'
-  ;;
-*)
-  resolution=$(xdpyinfo | awk '/dimensions/{print $2}')
-  make_blur_lock_screen
+        swaylock -f -K -i "/tmp/$wal_name" \
+            --font "mononoki Nerd Font" --font-size 30 \
+            --indicator-idle-visible --indicator-radius 100 --indicator-thickness 10 \
+            --ring-color "$color13" \
+            --text-color "$color15" \
+            --key-hl-color "$color12" \
+            --line-color "$color8" \
+            --inside-color "$color8" \
+            --separator-color "$color0" \
+            --inside-clear-color "$color11" --line-clear-color "$color12" --ring-clear-color "$color13"
+        # SWAYSOCK=/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock swaymsg 'output * dpms on'
+        ;;
+    *)
+        resolution=$(xdpyinfo | awk '/dimensions/{print $2}')
+        make_blur_lock_screen
 
-  i3lock -e -i "/tmp/$wal_name"
-  ;;
+        i3lock -e -i "/tmp/$wal_name"
+        ;;
 esac
