backlightctl: notify overhaul

diff --git a/bin/backlightctl b/bin/backlightctl
--- a/bin/backlightctl
+++ b/bin/backlightctl
@@ -6,134 +6,198 @@
 # control the percent delta of the brightness modification
 
 notify_echo() {
-  echo "$1"
-  notify-send "backlightctl" "$1"
+    echo "$1"
+    notify-send -h string:x-canonical-private-synchronous:backlightctl "backlightctl" "$1" 2>/dev/null \
+        || echo "Error: Cannot create notification"
 }
 
 [ -f /tmp/new_backlightctl_udev_rule ] && {
-  notify_echo >&2 "Error: You need to reboot for the udev rule to take effect"
-  exit 1
+    notify_echo >&2 "Error: You need to reboot for the udev rule to take effect"
+    exit 1
 }
 
 hash ddcutil 2>/dev/null || {
-  notify_echo >&2 "Error: ddcutil must be installed for external monitor control."
-  exit 1
+    notify_echo >&2 "Error: ddcutil must be installed for external monitor control."
+    exit 1
 }
 
 backlight_dev_dir=/sys/class/backlight
 backlight_devs=$(ls /sys/class/backlight)
 
-ddc_displays=$(ddcutil detect | awk '/^Display/{print $2}')
+ddc_displays=$(ddcutil detect 2>/dev/null | awk '/^Display/{print $2}')
 
-[ $backlight_devs ] || [ $ddc_displays ] || {
-  echo "Error: No configurable displays found! Sorry :("
-  exit 1
+[ "$backlight_devs" ] || [ "$ddc_displays" ] || {
+    echo "Error: No configurable displays found! Sorry :("
+    exit 1
 }
 
 [ "$UID" -eq 0 ] || {
-  user_in_video=false
-  for g in $(groups); do [ "$g" = video ] && user_in_video=true; done
+    user_in_video=false
+    for g in $(groups); do [ "$g" = video ] && user_in_video=true; done
 
-  $user_in_video || {
-    notify_echo >&2 "Error: $USER must be a member of the 'video' group for the udev rule"
-    exit 1
-  }
+    $user_in_video || {
+        notify_echo >&2 "Error: $USER must be a member of the 'video' group for the udev rule"
+        exit 1
+    }
 }
 
-if [ $backlight_devs ] && [ ! -f /etc/udev/rules.d/backlight.rules ]; then
-  [ "$UID" -eq 0 ] || {
-    notify_echo >&2 "Error: This script must be run as root while setting up the udev rule"
-    exit 1
-  }
-  mkdir -p /etc/udev/rules.d
+if [ "$backlight_devs" ] && [ ! -f /etc/udev/rules.d/backlight.rules ]; then
+    [ "$UID" -eq 0 ] || {
+        notify_echo >&2 "Error: This script must be run as root while setting up the udev rule"
+        exit 1
+    }
+    mkdir -p /etc/udev/rules.d
 
-  for dev in $backlight_devs; do
-    cat <<EOF >/etc/udev/rules.d/backlight.rules
+    for dev in $backlight_devs; do
+        cat <<EOF >/etc/udev/rules.d/backlight.rules
 ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video  ${backlight_dev_dir}/${dev}/brightness", RUN+="/bin/chmod g+w ${backlight_dev_dir}/${dev}/brightness"
 EOF
-  done
+    done
 
-  notify_echo "You'll need to reboot before the udev rule takes effect"
-  touch /tmp/new_backlightctl_udev_rule
-  exit 0
+    notify_echo "You'll need to reboot before the udev rule takes effect"
+    touch /tmp/new_backlightctl_udev_rule
+    exit 0
 fi
 
 brightness_percent_delta=1
 [ "$2" ] && brightness_percent_delta=$2
 
+print_bar() {
+    new_percent=$1
+
+    scale=2
+    num_squares=$((new_percent / scale))
+    num_underscores=$((100 / scale - num_squares))
+
+    for _ in $(seq "$num_squares"); do printf '▒'; done
+    for _ in $(seq "$num_underscores"); do printf '_'; done
+    printf '\n'
+}
+
 get() {
-  [ $backlight_devs ] && {
-    local current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
-    local max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
-    local interval=$((max_brightness / 100))
+    [ "$backlight_devs" ] && {
+        local current_brightness max_brightness interval
 
-    for dev in $backlight_devs; do
-      echo $((current_brightness * 100 / max_brightness))
+        for dev in $backlight_devs; do
+            current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
+            max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
+            interval=$((max_brightness / 100))
+
+            notify_echo "($((current_brightness * 100 / max_brightness))%) $(print_bar $((current_brightness * 100 / max_brightness)))"
+        done
+    }
+
+    for display in $ddc_displays; do
+        printf "Display %s: " "$display"
+        ddcutil -t get 10 --display "$display" | awk '{print $4}'
     done
-  }
-
-  for display in $ddc_displays; do
-    ddcutil get 10 --display $display
-  done
 }
 
 up() {
-  [ $backlight_devs ] && {
-    local current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
-    local max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
-    local interval=$((max_brightness / 100))
+    [ "$backlight_devs" ] && {
+        local current_brightness max_brightness interval
 
-    for dev in $backlight_devs; do
-      echo $((current_brightness + (interval * brightness_percent_delta))) >"${backlight_dev_dir}/${dev}/brightness"
+        for dev in $backlight_devs; do
+            current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
+            max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
+            interval=$((max_brightness / 100))
+
+            new_brightness=$((current_brightness + (interval * brightness_percent_delta)))
+            new_percent=$((current_brightness * 100 / max_brightness + brightness_percent_delta))
+
+            [ $new_brightness -gt "$max_brightness" ] && {
+                notify_echo "Error: Brightness cannot be set above $max_brightness. Current brightness is $current_brightness"
+                exit 1
+            }
+
+            echo $new_brightness >"${backlight_dev_dir}/${dev}/brightness" || {
+                notify_echo "Error: Failed to update backlight
+DEBUG: current_brightness=$current_brightness
+DEBUG: max_brightness=$max_brightness
+DEBUG: new_brightness=$new_brightness
+                            "
+                exit 1
+            }
+            notify_echo "($new_percent%) $(print_bar "$new_percent")"
+        done
+    }
+
+    for display in $ddc_displays; do
+        display_brightness=$(ddcutil -t get 10 --display "$display" | awk '{print $4}')
+        ddcutil set 10 $((display_brightness + brightness_percent_delta)) --display "$display"
     done
-  }
-
-  for display in $ddc_displays; do
-    display_brightness=$(ddcutil get 10 --display $display)
-    ddcutil set 10 40 --display $display
-  done
 }
 
 down() {
-  [ $backlight_devs ] && {
-    local current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
-    local max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
-    local interval=$((max_brightness / 100))
+    [ "$backlight_devs" ] && {
+        local current_brightness max_brightness interval
 
-    for dev in $backlight_devs; do
-      echo $((current_brightness - (interval * brightness_percent_delta))) >"${backlight_dev_dir}/${backlight_devs}/brightness"
+        for dev in $backlight_devs; do
+            current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
+            max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
+            interval=$((max_brightness / 100))
+
+            new_brightness=$((current_brightness - (interval * brightness_percent_delta)))
+            new_percent=$((current_brightness * 100 / max_brightness - brightness_percent_delta))
+
+            [ $new_brightness -lt 0 ] && {
+                echo "Error: Brightness cannot be set below 0"
+                exit 1
+            }
+
+            echo $new_brightness >"${backlight_dev_dir}/${backlight_devs}/brightness" || {
+                notify_echo "Error: Failed to update backlight
+DEBUG: current_brightness=$current_brightness
+DEBUG: max_brightness=$max_brightness
+DEBUG: new_brightness=$new_brightness
+                            "
+                exit 1
+            }
+            notify_echo "($new_percent%) $(print_bar "$new_percent")"
+        done
+    }
+
+    for display in $ddc_displays; do
+        display_brightness=$(ddcutil -t get 10 --display "$display" | awk '{print $4}')
+        ddcutil set 10 $((display_brightness - brightness_percent_delta)) --display "$display"
     done
-  }
-
-  for display in $ddc_displays; do
-    display_brightness=$(ddcutil get 10 --display $display)
-    ddcutil set 10 40 --display $display
-  done
 }
 
 change() {
-  new_percent=$(seq 1 100 | fuzzel -d -p "new brightness >")
+    new_percent=$(seq 1 100 | fuzzel -d -p "new brightness >")
 
-  [ $backlight_devs ] && {
-    local current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
-    local max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
-    local interval=$((max_brightness / 100))
+    [ "$backlight_devs" ] && {
+        local current_brightness max_brightness interval
 
-    for dev in $backlight_devs; do
-      echo $((new_percent * interval)) >"${backlight_dev_dir}/${backlight_devs}/brightness"
+        for dev in $backlight_devs; do
+            current_brightness=$(cat "${backlight_dev_dir}/${dev}/brightness")
+            max_brightness=$(cat "${backlight_dev_dir}/${dev}/max_brightness")
+            interval=$((max_brightness / 100))
+
+            new_brightness=$((new_percent * interval))
+
+            echo $new_brightness >"${backlight_dev_dir}/${backlight_devs}/brightness" || {
+                notify_echo "Error: Failed to update backlight
+DEBUG: current_brightness=$current_brightness
+DEBUG: max_brightness=$max_brightness
+DEBUG: new_brightness=$new_brightness
+                            "
+                exit 1
+            }
+            notify_echo "($new_percent%) $(print_bar "$new_percent")"
+        done
+    }
+
+    for display in $ddc_displays; do
+        display_brightness=$(ddcutil get 10 --display "$display")
+        ddcutil set 10 "$new_percent" --display "$display"
     done
-  }
-
-  for display in $ddc_displays; do
-    display_brightness=$(ddcutil get 10 --display $display)
-    ddcutil set 10 $new_percent --display $display
-  done
 }
 
 case $1 in
-up | down | change | get) $1 ;;
-*)
-  echo >&2 "Error: Unsupported option $1. Valid options are: [up, down, get]"
-  exit 1
-  ;;
+    up | down | change | get) $1 ;;
+    *)
+        echo >&2 "Error: Unsupported option $1. Valid options are: [up, down, get, change]"
+        exit 1
+        ;;
 esac
